import './polyfills.mjs';
import TestDirector from 'test-director';
import testBundle from './bundle.test.mjs';
import testCreateArgErrorMessageProd from './private/createArgErrorMessageProd.test.mjs';
import testUseForceUpdate from './private/useForceUpdate.test.mjs';
import testCache from './public/Cache.test.mjs';
import testCacheContext from './public/CacheContext.test.mjs';
import testHYDRATION_TIME_MS from './public/HYDRATION_TIME_MS.test.mjs';
import testHydrationTimeStampContext from './public/HydrationTimeStampContext.test.mjs';
import testLoading from './public/Loading.test.mjs';
import testLoadingCacheValue from './public/LoadingCacheValue.test.mjs';
import testLoadingContext from './public/LoadingContext.test.mjs';
import testProvider from './public/Provider.test.mjs';
import testCacheDelete from './public/cacheDelete.test.mjs';
import testCacheEntryDelete from './public/cacheEntryDelete.test.mjs';
import testCacheEntryPrune from './public/cacheEntryPrune.test.mjs';
import testCacheEntrySet from './public/cacheEntrySet.test.mjs';
import testCacheEntryStale from './public/cacheEntryStale.test.mjs';
import testCachePrune from './public/cachePrune.test.mjs';
import testCacheStale from './public/cacheStale.test.mjs';
import testFetchGraphQL from './public/fetchGraphQL.test.mjs';
import testFetchOptionsGraphQL from './public/fetchOptionsGraphQL.test.mjs';
import testUseAutoAbortLoad from './public/useAutoAbortLoad.test.mjs';
import testUseAutoLoad from './public/useAutoLoad.test.mjs';
import testUseCache from './public/useCache.test.mjs';
import testUseCacheEntry from './public/useCacheEntry.test.mjs';
import testUseCacheEntryPrunePrevention from './public/useCacheEntryPrunePrevention.test.mjs';
import testUseLoadGraphQL from './public/useLoadGraphQL.test.mjs';
import testUseLoadOnDelete from './public/useLoadOnDelete.test.mjs';
import testUseLoadOnMount from './public/useLoadOnMount.test.mjs';
import testUseLoadOnStale from './public/useLoadOnStale.test.mjs';
import testUseLoading from './public/useLoading.test.mjs';
import testUseLoadingEntry from './public/useLoadingEntry.test.mjs';
import testUseWaterfallLoad from './public/useWaterfallLoad.test.mjs';

const tests = new TestDirector();

testCreateArgErrorMessageProd(tests);
testUseForceUpdate(tests);
testCache(tests);
testCacheContext(tests);
testCacheDelete(tests);
testCacheEntryDelete(tests);
testCacheEntryPrune(tests);
testCacheEntrySet(tests);
testCacheEntryStale(tests);
testCachePrune(tests);
testCacheStale(tests);
testFetchGraphQL(tests);
testFetchOptionsGraphQL(tests);
testHYDRATION_TIME_MS(tests);
testHydrationTimeStampContext(tests);
testLoading(tests);
testLoadingCacheValue(tests);
testLoadingContext(tests);
testProvider(tests);
testUseAutoAbortLoad(tests);
testUseAutoLoad(tests);
testUseCache(tests);
testUseCacheEntry(tests);
testUseCacheEntryPrunePrevention(tests);
testUseLoadGraphQL(tests);
testUseLoading(tests);
testUseLoadingEntry(tests);
testUseLoadOnDelete(tests);
testUseLoadOnMount(tests);
testUseLoadOnStale(tests);
testUseWaterfallLoad(tests);
testBundle(tests);

tests.run();
