import './polyfills.mjs';
import TestDirector from 'test-director';
import test_bundle from './bundle.test.mjs';
import test_createArgErrorMessageProd from './private/createArgErrorMessageProd.test.mjs';
import test_useForceUpdate from './private/useForceUpdate.test.mjs';
import test_Cache from './public/Cache.test.mjs';
import test_CacheContext from './public/CacheContext.test.mjs';
import test_HYDRATION_TIME_MS from './public/HYDRATION_TIME_MS.test.mjs';
import test_HydrationTimeStampContext from './public/HydrationTimeStampContext.test.mjs';
import test_Loading from './public/Loading.test.mjs';
import test_LoadingCacheValue from './public/LoadingCacheValue.test.mjs';
import test_LoadingContext from './public/LoadingContext.test.mjs';
import test_Provider from './public/Provider.test.mjs';
import test_cacheDelete from './public/cacheDelete.test.mjs';
import test_cacheEntryDelete from './public/cacheEntryDelete.test.mjs';
import test_cacheEntryPrune from './public/cacheEntryPrune.test.mjs';
import test_cacheEntrySet from './public/cacheEntrySet.test.mjs';
import test_cacheEntryStale from './public/cacheEntryStale.test.mjs';
import test_cachePrune from './public/cachePrune.test.mjs';
import test_cacheStale from './public/cacheStale.test.mjs';
import test_fetchGraphQL from './public/fetchGraphQL.test.mjs';
import test_fetchOptionsGraphQL from './public/fetchOptionsGraphQL.test.mjs';
import test_useAutoAbortLoad from './public/useAutoAbortLoad.test.mjs';
import test_useAutoLoad from './public/useAutoLoad.test.mjs';
import test_useCache from './public/useCache.test.mjs';
import test_useCacheEntry from './public/useCacheEntry.test.mjs';
import test_useCacheEntryPrunePrevention from './public/useCacheEntryPrunePrevention.test.mjs';
import test_useLoadGraphQL from './public/useLoadGraphQL.test.mjs';
import test_useLoadOnDelete from './public/useLoadOnDelete.test.mjs';
import test_useLoadOnMount from './public/useLoadOnMount.test.mjs';
import test_useLoadOnStale from './public/useLoadOnStale.test.mjs';
import test_useLoading from './public/useLoading.test.mjs';
import test_useLoadingEntry from './public/useLoadingEntry.test.mjs';
import test_useWaterfallLoad from './public/useWaterfallLoad.test.mjs';

const tests = new TestDirector();

test_createArgErrorMessageProd(tests);
test_useForceUpdate(tests);
test_Cache(tests);
test_CacheContext(tests);
test_cacheDelete(tests);
test_cacheEntryDelete(tests);
test_cacheEntryPrune(tests);
test_cacheEntrySet(tests);
test_cacheEntryStale(tests);
test_cachePrune(tests);
test_cacheStale(tests);
test_fetchGraphQL(tests);
test_fetchOptionsGraphQL(tests);
test_HYDRATION_TIME_MS(tests);
test_HydrationTimeStampContext(tests);
test_Loading(tests);
test_LoadingCacheValue(tests);
test_LoadingContext(tests);
test_Provider(tests);
test_useAutoAbortLoad(tests);
test_useAutoLoad(tests);
test_useCache(tests);
test_useCacheEntry(tests);
test_useCacheEntryPrunePrevention(tests);
test_useLoadGraphQL(tests);
test_useLoading(tests);
test_useLoadingEntry(tests);
test_useLoadOnDelete(tests);
test_useLoadOnMount(tests);
test_useLoadOnStale(tests);
test_useWaterfallLoad(tests);
test_bundle(tests);

tests.run();
